Repository ko-tarou/hackthon2024-12, pull requests merged in 2024-11, with the labels that each got.

#1 共有開始
  src/pages/Toppage.js
Labels: base

#2 やばい変更　フォルダ分けちゃった
  package-lock.json
  package.json
  src/pages/Projectpage.js
  src/pages/Toppage.js
Labels: base

#3 データ送信no
  src/pages/Toppage.js
Labels: base

#4 環境完成
  package-lock.json
  package.json
  src/pages/Projectpage.js
  src/pages/Toppage.js
Labels: base

#5 環境共有
  package-lock.json
  package.json
  src/pages/Projectpage.js
  src/pages/Toppage.js
Labels: base

#6 音声認識完成
  src/pages/Toppage.js
Labels: back

#7 動かせるテキストボックス
  package-lock.json
  package.json
  src/common/MovableTextBox.js
  src/pages/Toppage.js
Labels: ui

#8 slidepageの大まかな構成完成
  src/App.css
  src/App.js
  src/pages/Slidepage.js
  src/styles/Slidepage.css
Labels: ui

#9 構成の微調整
  src/pages/Slidepage.js
  src/styles/Slidepage.css
Labels: ui

#10 tabsコンポーネントの作成
  src/App.js
  src/common/object-list-tab/TabContent.js
  src/common/object-list-tab/TabMain.js
  src/common/object-list-tab/Tabs.js
  src/pages/Slidepage.js
  src/styles/Slidepage.css
Labels: ui

#11 Tabの機能完成
  src/common/object-list-tab/TabContent.js
  src/common/object-list-tab/TabMain.js
  src/common/object-list-tab/Tabs.js
  src/pages/Slidepage.js
Labels: ui

#12 テキストボックスの追加・移動機能
  package-lock.json
  package.json
  src/App.js
  src/common/MovableTextBox.js
  src/common/drop/DraggableTextBox.js
  src/common/drop/DropZone.js
  src/common/drop/ItemTypes.js
  src/common/drop/TextBox.js
  src/common/drop/TextBoxArea.js
  src/common/object-list-tab/TabContent.js
  src/common/object-list-tab/Tabs.js
  src/pages/Slidepage.js
  src/pages/TestPage.js
  src/pages/tabs/Char.js
  src/styles/tabs/Char.css
Labels: ui

#13 テキストボックスの削除
  src/common/drop/DropZone.js
  src/common/drop/TextBox.js
  src/common/drop/TextBoxArea.js
  src/pages/Slidepage.js
  src/pages/tabs/Char.js
Labels: ui

#14 名前の追加
  src/pages/Toppage.js
Labels: ui

#15 テキストボックスは完成
  package-lock.json
  package.json
  src/common/drop/DropZone.js
  src/common/drop/TextBox.js
  src/common/drop/useWebSocket.js
  src/pages/Projectpage.js
  src/pages/Slidepage.js
Labels: ui

#19 岩崎first commit
  src/pages/TopPage/TopPage.js
Labels: ui

#20 Feature/create title
  src/pages/TestPage/TestPage.css
  src/pages/TestPage/TestPage.js
  src/pages/TopPage/TopPage.js
Labels: ui

#21 ボタン完成‼
  src/App.css
  src/pages/TopPage/TopPage.js
Labels: ui

#22 Feature/create -newbuttom
  src/pages/TestPage/TestPage.css
  src/pages/TestPage/TestPage.js
Labels: ui

#23 コンポーネント作成
  src/pages/SlideList/SlideList.css
  src/pages/SlideList/SlideList.js
  src/pages/SlidePage/SlidePage.js
  src/pages/TopPage/TopPage.js
Labels: ui

#25 はてなマーク完成
  src/App.css
  src/App.js
Labels: ui

#26 Feture/create bottom padding
  src/App.css
Labels: ui

#27 Feature/crete-s
  src/App.js
  src/pages/SlideView/SlideView.css
  src/pages/SlideView/SlideView.js
Labels: ui

#28 保存機能追加
  src/pages/SlidePage/SlidePage.js
Labels: back

#29 Feature/create text field
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: ui

#33 ？マーク説明書
  src/App.css
  src/App.js
  src/components/hint_circle-button/hint_circle-button.css
  src/components/hint_circle-button/hint_circle-button.js
Labels: ui

#34 Feature/create question modal2
  src/pages/SlidePage/SlidePage.css
  src/pages/TestPage/TestPage.js
Labels: ui

#35 ボタンを押すとスライドページにとぶ
  src/pages/TestPage/TestPage.js
Labels: ui

#36 下のボタン完成
  src/pages/TestPage/TestPage.js
Labels: ui

#37 Feature/iwasaki
  src/pages/SlideList/SlideList.css
  src/pages/SlideList/SlideList.js
Labels: ui

#38 Feature/create rightside slide
  src/pages/SlideView/SlideView.css
  src/pages/SlideView/SlideView.js
Labels: ui

#39 SlidePageにSlideListのやつ加えたっていい
  src/pages/SlideList/SlideList.js
  src/pages/SlidePage/SlidePage.js
Labels: ui
